<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.3.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Scripting.Common" Version="5.3.0" />
    <PackageVersion Include="NuGet.Commands" Version="7.6.0" />
    <PackageVersion Include="System.Text.Json" Version="10.0.9" />
  </ItemGroup>
</Project>